### ISSUE TITLE
Testing issue when rpn_stride is changed

### ISSUE THREAD

**Issue by mannipa** [yhenon/keras-frcnn#151]
Hi, recently I changed rpn_stride from 16 to 8 in config.py and started training on my own data set based on resnet50_weights_tf_dim_ordering_tf_kernels.h5. Everything goes well until the training finished with 98% accuracy then I got a terrible test result (almost zero accuracy) on same data set used to train. I use test_frcnn.py to do the test.

Shall I modify something to go with rpn_stride changes?

Thanks.

**Comment by thealchemist89** [comment]
Hi @mannipa ,

If you change rpn_stride from 16 to 8, you will likely need to extract features from conv3_x layer instead of the current conv4_x layer.

I am assuming you left resnet.py untouched and simply change rpn_stride to 8. If that's the case, you may need to investigate the above comments.

Good luck!

**Comment by mannipa** [comment]
Thanks. I also found previors post that talking about this.

**Comment by mannipa** [comment]
Thanks. I also found previors post that talking about this.
