### ISSUE TITLE
Improper Bounding box

### ISSUE THREAD

**Issue by himanshurobo** [yhenon/keras-frcnn#18]
Hi @yhenon ,
I have used this code for VOC data sets for testing purpose. But i am not getting proper bounding box. for example 
160 208 704 592 person:92
64 32 448 608 person:91
608 112 1040 608 person:90
288 -16 720 576 person:90
128 -16 592 496 person:87
0 -16 320 576 person:86
800 -16 1056 480 person:72
480 0 1040 480 person:69

Do you have any idea why i am not getting proper bbox and the position as well.

![00](https://cloud.githubusercontent.com/assets/14348226/25171579/f652043a-250b-11e7-8fc7-0d193e88d3ae.jpg)

**Comment by yhenon** [comment]
Hi,
I've pushed an update which fixes issues and should help somewhat. In general though, overlapping objects of the same class often have poor quality boxes, even in the original implementation. This is likely because the regression layer in the classifier cannot know which ground truth box to regress to, so it gives poor results.
