### ISSUE TITLE
Bounding box regression done twice?

### ISSUE THREAD

**Issue by shinstra** [yhenon/keras-frcnn#189]
I was wondering if there is a reason why both the rpn and classifier parts of the model have bounding box regression layers (instead of just in the rpn part). These regression layers also seem to be very different - in the rpn, it generates a regression for every anchor proposal; and in the classifier, it generates class specific regressions. 

I haven't been able to find the later regression described in the paper. My best guess here is that it is an add-on for introducing a class biased regression correction.

**Comment by Tbarowski** [comment]
> I haven't been able to find the later regression described in the paper. My best guess here is that it is an add-on for introducing a class biased regression correction.

I think this is correct. It can not be done at the rpn phase because the classification is reduced to object and non-object. The doubled regression says imo that its redefinement is kind of limited. There are papers (e.g. DeepManta) that use even more of these refinement steps and claim that this is good for performance.

**Comment by shinstra** [comment]
Kool, thanks for the tip. 

Looking back in the series of papers I eventually found it in the Fast R-CNN paper.
