### ISSUE TITLE
[Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Main/test.txt'

### ISSUE THREAD

**Issue by kevinkit** [yhenon/keras-frcnn#22]
Executing the train_frcnn.py gives me the error 

> [Errno 2] No such file or directory: 'VOCdevkit/VOC2012/ImageSets/Main/test.txt'

However the program does not crash, it just continues training - so what is this file and why is it looking for it? Is the actual annotation of training data? And why is it missing?

**Comment by xuewenyuan** [comment]
I met the same error. I think that's because the trian data and test data of VOC are not in the same folder. You can download the test data of VOC2007 from [http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar](http://host.robots.ox.ac.uk/pascal/VOC/voc2007/VOCtest_06-Nov-2007.tar).
But there are still some code about "_test_" in [pascal_voc_parser.py](https://github.com/yhenon/keras-frcnn/blob/master/keras_frcnn/pascal_voc_parser.py) .
For the approach of test, test_frcnn.py can be used. 
Waiting for the update of this problem.

**Comment by arnaudmiribel** [comment]
+1 
Same here, but the program does crash...

```
Parsing annotation files
[Errno 2] No such file or directory: 'data/VOCdevkit/VOC2012/ImageSets/Main/test.txt'
Traceback (most recent call last):
  File "train_frcnn.py", line 78, in <module>
    inv_map = {v: k for k, v in class_mapping.iteritems()}
```

**Comment by yhenon** [comment]
Fixed.
