### ISSUE TITLE
Slow training times & Exceptions

### ISSUE THREAD

**Issue by tkcossio** [yhenon/keras-frcnn#29]
Hey @yhenon - how long should training take per epoch?  I'm running train_frcnn on a machine with 1 K80 (TF configured for GPU support) and each epoch is taking ~20 minutes.  Is this expected?

Also seeing a number of Exceptions during training, e.g.
Exception:
Exception: 'NoneType' object has no attribute '__getitem__'

Any ideas for either of these issues?

**Comment by Tuzoff** [comment]
If you’re training it on 1000 iterations, I think this is a very good performance. Previously it was much slower. We have a similar performance now

**Comment by tkcossio** [comment]
Good to know!  How many epochs would you expect for convergence?

**Comment by GabrielGlzSa** [comment]
I trained for 100 epochs and took around 10 hours on a gtx 1050 ti. The elapsed time of each epoch was around 360-400 seconds. However I am training using less ROIs (10) than default (32) and I resize to 300 since I don't have enough memory.
It wasn't enough as the only class that often detects is person. The other ones are detected rarely or none at all.
Test takes on average 5 seconds per photo on CPU and 0.5 on GPU.

**Comment by tkcossio** [comment]
Was able to achieve 60.0% mAP after 30 epochs.  @GabrielGlzSa make sure you download the resnet pre-trained weights first (it's easy to miss the warning).
