### ISSUE TITLE
Confused with the use of C.rpn_min_overlap and C.rpn_max_overlap

### ISSUE THREAD

**Issue by Crul** [yhenon/keras-frcnn#30]
Hi,
I was looking at the code and I'm confused with the use of C.rpn_min_overlap and C.rpn_max_overlap.

In data_generators.py, the samples with an iou between those values are marked as neutral:
https://github.com/yhenon/keras-frcnn/blob/master/keras_frcnn/data_generators.py#L197-L201
```
  # if the IOU is >0.3 and <0.7, it is ambiguous and no included in the objective
  if C.rpn_min_overlap < curr_iou < C.rpn_max_overlap:
      # gray zone between neg and pos
      if bbox_type != 'pos':
          bbox_type = 'neutral'
```
But in roi_helpers, the values between C.rpn_min_overlap and C.rpn_max_overlap are marked as 'bg' (the negative class), and those bellow C.rpn_min_overlap are ignored:
https://github.com/yhenon/keras-frcnn/blob/master/keras_frcnn/roi_helpers.py#L44-L53

In previous version of roi_helpers there are even comments with the conditions I was expecting but they don't match with the code (the comments were removed in the last commit):
https://github.com/yhenon/keras-frcnn/blob/0c5caf02550e92e333409685ae9e4a3afc4104aa/keras_frcnn/roi_helpers.py#L45-L56
```
  #if 0.1 < best_iou < 0.7:
  if best_iou < C.classifier_min_overlap:
      continue
  else:
      w = x2 - x1
      h = y2 - y1
      x_roi.append([x1, y1, w, h])

      #if best_iou <= 0.1:
      if C.classifier_min_overlap <= best_iou < C.classifier_max_overlap:
        # hard negative example
        cls_name = 'bg'
```

So, is there any intention in the different use of the ranges?
[Edit: I can imagine that the purpose could be to train the classifier with positives and near positives, but not sure about that interpretation. And I've realized there are different overlap thresholds.]

Thank you very much!

**Comment by yhenon** [comment]
Although `rpn_min_overlap` and `classifier_min_overlap` sound similar, they are used differently. You will need to read the original faster rcnn paper for full details. Briefly:
- in the RPN, we define a gray zone between `rpn_min_overlap` and `rpn_max_overlap` where no training is done, so that the RPN is only trained on clear object/background samples.
- in the classifier, we select which samples to train on. Objects with an IoU > `classifier_max_overlap` (almost always 0.5) are the positive samples. For negative samples, we want to pick somewhat hard examples, so we only use samples that partially overlap the object, so `classifier_min_overlap < IoU < classifier_max_overlap`

I'm going to close this as it is not an issue with the code.

**Comment by Crul** [comment]
That's exactly what I thought after posting the question.
And sorry if this is the wrong place to ask. Thank you very much.

**Comment by yhenon** [comment]
No problem! It could probably use some more documentation.
