### ISSUE TITLE
Using fit over train_batch

### ISSUE THREAD

**Issue by Ahleroy** [yhenon/keras-frcnn#58]
In the train_frcnn.py file we use train_batch for both model_classifier and model_rpn. What are the advantages of using this function instead of the fit function directly on the model_all ? 

How could I add the tensorboard callback to the train_batch function?

Regards.

**Comment by yhenon** [comment]
`train_on_batch` does 1 batch for 1 epoch, which is what we do in train_frcnn, since there is lots of extra code to generate the ground truth and parse the results from the RPN. `fit` is used for multiple batches of data for multiple epochs.

the tensorboard callback is not very flexible unfortunately - I see no easy way to integrate it
