### ISSUE TITLE
Is missing a classes.json archive

### ISSUE THREAD

**Issue by joseildofilho** [yhenon/keras-frcnn#9]
When i try to run the NN, i've received the follow message:
`File "test_frcnn.py", line 40, in <module>
    with open('classes.json', 'r') as class_data_json:
IOError: [Errno 2] No such file or directory: 'classes.json'
`

**Comment by Timonzimm** [comment]
You have to run the training beforehand so the classes are parsed form your ground truth file (with simple_parser.py) or from the pascal voc annotation files (with pascal_voc_parser.py).

I don't know if we have a solution to create this classes.json file from a model for example, you could create it manually otherwise.

**Comment by yhenon** [comment]
As @Timonzimm said, you can only run the testing once you have a trained model. I'll distribute weights/JSON files when the code is at a more final stage.
