### ISSUE TITLE
get_output_length

### ISSUE THREAD

**Issue by Ahleroy** [yhenon/keras-frcnn#94]
Hello,

I have found how to solve the issue #56 . The problem is located into the file data_generator.py into the method `get_output_length`

     def get_img_output_length(width, height):
          def get_output_length(input_length):
          # zero_pad
	  input_length += 6
	  # apply 4 strided convolutions
	  filter_sizes = [7, 3, 1, 1]
          stride = 2
	  for filter_size in filter_sizes:
		input_length = (input_length - filter_size + stride) // stride
	  return input_length

     return get_output_length(width), get_output_length(height)`

Before modifying the file, I would like to know how the `input_length` padding, the `filter_sizes` and the `stride` have been selected.

Regards,

**Comment by olaff09** [comment]
Hi Ahleroy, from what I know, the numers are like this:

filter_sizes = These are selected from the convolutions in the net (ResNet) that have a stride of 2, if you look carefully, on the base network there are 4 convolutions that have a stride of 2, and their filter sizes are specifically [7, 3, 1, 1], and that is also the reason you have stride = 2 and multiply it by each of the filter sizes.

This calculation is done because a stride of 2 reduces the feature map area (by half), you need to know the final width / height  of the feature map, which is reduced from these convolutions.

**Comment by yhenon** [comment]
@olaff09 is indeed correct. I just pushed support for vgg architecture, you can see the image length calculation for vgg is very simple:
```
def get_img_output_length(width, height):
    def get_output_length(input_length):
        return input_length/16

    return get_output_length(width), get_output_length(height)    
```
